@baseUrl  = http://localhost:5275/api/Auth

###
# @name register
POST {{baseUrl}}/Register HTTP/1.1
content-type: application/json

{
    "name": "askdmokqasmdoasmd",
    "email": "ajosndqojas@email.com",
    "password": "sadmoka#1sdkA"
}


###
# @name login
POST {{baseUrl}}/Login HTTP/1.1
content-type: application/json

{
    "email": "ajosndojas@email.com",
    "password": "sadmokasdk!2A"
}

@authToken = {{login.response.body.$.result}}

Authorization: {{authToken}}