
@baseUrl  = http://localhost:5275/api
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhYTI0YjNmLWUxZWQtNDM1ZC1iOGZmLTRhMDYxOTcwZmUyMiIsIm5hbWVpZCI6ImRhYTI0YjNmLWUxZWQtNDM1ZC1iOGZmLTRhMDYxOTcwZmUyMiIsImVtYWlsIjoiTXlfdXNlcm5hbWVAZW1haWwuY29tIiwianRpIjoiOWNiNjBlMjQtZTUxNS00NWU5LWFhNjktZTkzNjY2MGE2NjE1IiwiaWF0IjoxNjk5NDczOTE5LCJuYmYiOjE2OTk0NzM5MTksImV4cCI6MTY5OTQ4ODMxOX0.wZqh75TFQ7FsYi4tZ91gyneAaox5jZ9qeNYlMczbXWk

###
# @name createProject
POST {{baseUrl}}/Project HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "name" : "Big House",
    "address": {
        "street":"Av. B P S, 1303",
        "city":"Itajubá",
        "state":"Minas Gerais",
        "zipcode":"37500-903",
        "country":"Brasil",
    }
}


###
# @name getProject
GET {{baseUrl}}/Project/GetProjectById HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "id" : "4c504c5b-0d18-4dc7-8f4b-ef30bc56f0d1",
}



###
# @name addUserProject
POST {{baseUrl}}/Project/AddUser HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "userid" : "daa24b3f-e1ed-435d-b8ff-4a061970fe22",
    "projectid" : "4c504c5b-0d18-4dc7-8f4b-ef30bc56f0d1",
    "role": "worker"
}


