@baseUrl  = http://localhost:5275/api
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA2NDUwZjYxLThhMzItNDNhZi04MzI0LWY3MTc2M2U2MmU2YiIsIm5hbWVpZCI6IjA2NDUwZjYxLThhMzItNDNhZi04MzI0LWY3MTc2M2U2MmU2YiIsImVtYWlsIjoiTXlfdXNlcm5hbWVAZW1haWwuY29tIiwianRpIjoiZTJhMjQ3MDMtOGUwYS00YTBmLWJlMDktN2MxYWEyMmQ2YTQ0IiwiaWF0IjoxNjk5NDcwNjQyLCJuYmYiOjE2OTk0NzA2NDIsImV4cCI6MTY5OTQ4NTA0Mn0.N5R9jN8rGQ-do_i0aHxSk4HYnPi4R2y6FFu5lam9FNw



###
# @name getUser
GET {{baseUrl}}/User HTTP/1.1
accept: text/plain
Authorization: Bearer {{authToken}}


###
# return all users
@queryName = all
# return a single user according to his username
# @queryName = Joao_Silva
# @QueryProject = Project


# @name getAnotherUser
GET {{baseUrl}}/User?username={{queryName}} HTTP/1.1
accept: text/plain
Authorization: Bearer {{authToken}}


###
# @name deleteUser
DELETE {{baseUrl}}/User HTTP/1.1
accept: text/plain
Authorization: Bearer {{authToken}}

{
    "password" : ""
}

###
# @name updateUser
PUT {{baseUrl}}/User HTTP/1.1
accept: text/plain
Authorization: Bearer {{authToken}}
content-type: application/json

{    
    "username" : "JoaoSilva2685",
    "firstname": "Joao",
    "lastname": "Silva",
    "email": "ajosnaaadoaaajas@email.com",
    "photopath": ""
}