@baseUrl  = http://localhost:5275/api
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhYTI0YjNmLWUxZWQtNDM1ZC1iOGZmLTRhMDYxOTcwZmUyMiIsIm5hbWVpZCI6ImRhYTI0YjNmLWUxZWQtNDM1ZC1iOGZmLTRhMDYxOTcwZmUyMiIsImVtYWlsIjoiTXlfdXNlcm5hbWVAZW1haWwuY29tIiwianRpIjoiN2E2YjI2ODYtNmZiZS00ZDNjLTk1NmUtNWYwNGI2ZDlhY2QzIiwiaWF0IjoxNjk5NDgwOTQ4LCJuYmYiOjE2OTk0ODA5NDgsImV4cCI6MTY5OTQ5NTM0OH0.NKBr4NPKWXpXwOPprQAp61sebJczLCSiDhZcR47GNXQ


###
# @name getUser
GET {{baseUrl}}/User HTTP/1.1
accept: text/plain
Authorization: Bearer {{authToken}}


###
# return all users
@queryName = all
# return a single user according to his username
# @queryName = Joao_Silva
# @QueryProject = Project


# @name getAnotherUser
GET {{baseUrl}}/User/all?username={{queryName}} HTTP/1.1
accept: text/plain
Authorization: Bearer {{authToken}}


###
# @name deleteUser
DELETE {{baseUrl}}/User HTTP/1.1
accept: text/plain
Authorization: Bearer {{authToken}}

{
    "password" : ""
}

###
# @name updateUser
PUT {{baseUrl}}/User HTTP/1.1
accept: text/plain
Authorization: Bearer {{authToken}}
content-type: application/json

{    
    "username" : "JoaoSilva2685",
    "firstname": "Joao",
    "lastname": "Silva",
    "email": "ajosnaaadoaaajas@email.com",
    "photopath": ""
}